"""Interval Decision Audit Log Explorer.

Displays the complete audit trail of every 15-minute dispatch interval
read directly from the structured JSONL audit logs.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import pandas as pd
import streamlit as st

from app.shared import init_session_state

st.set_page_config(page_title="Decision Log — GridMind", page_icon="📜", layout="wide")
init_session_state()

orch = st.session_state.orchestrator
log_entries = orch.logger.read_all_entries()

st.title("📜 15-Minute Decision Audit Trail")
st.markdown("Filter and inspect the immutable structured audit log generated by GridMind across every dispatch interval.")

if not log_entries:
    st.info("No decision records exist in the current run log. Execute intervals from the Control Room to populate the audit trail.")
    st.stop()

# Convert entries to tabular format
flat_records = []
for entry in log_entries:
    tel = entry.get("telemetry", {})
    disp = entry.get("dispatch", {})
    mon = entry.get("monitor") or {}
    strat = entry.get("strategy") or {}
    met = entry.get("metrics", {})
    exp = entry.get("explanation") or {}

    flat_records.append({
        "Interval": entry.get("interval_index"),
        "Timestamp": entry.get("timestamp"),
        "Mode": strat.get("mode", "green"),
        "Severity": mon.get("severity", "low"),
        "Solar (MW)": tel.get("solar_actual_mw", 0.0),
        "Wind (MW)": tel.get("wind_actual_mw", 0.0),
        "Demand (MW)": tel.get("demand_actual_mw", 0.0),
        "IEX Price (₹)": tel.get("price_actual_inr_per_mwh", 0.0),
        "Grid Import (MW)": disp.get("grid_import_mw", 0.0),
        "Grid Export (MW)": disp.get("grid_export_mw", 0.0),
        "Shortfall (MW)": disp.get("shortfall_mw", 0.0),
        "Unserved Critical (MW)": disp.get("unserved_critical_mw", 0.0),
        "Net Cost (₹)": met.get("total_net_cost_inr", 0.0),
        "Carbon (tCO₂)": met.get("carbon_emissions_tco2", 0.0),
        "Safe Mode": entry.get("is_safe_mode", False),
        "Headline": exp.get("headline", ""),
    })

df_logs = pd.DataFrame(flat_records)

# Filter Controls
col_f1, col_f2, col_f3 = st.columns(3)
with col_f1:
    modes_avail = ["All"] + sorted(list(df_logs["Mode"].unique()))
    sel_mode = st.selectbox("Filter by Operating Mode", modes_avail)
with col_f2:
    sev_avail = ["All"] + sorted(list(df_logs["Severity"].unique()))
    sel_sev = st.selectbox("Filter by Anomaly Severity", sev_avail)
with col_f3:
    max_int = int(df_logs["Interval"].max())
    int_range = st.slider("Interval Range", 0, max(1, max_int), (0, max_int))

# Apply filters
df_filtered = df_logs.copy()
if sel_mode != "All":
    df_filtered = df_filtered[df_filtered["Mode"] == sel_mode]
if sel_sev != "All":
    df_filtered = df_filtered[df_filtered["Severity"] == sel_sev]
df_filtered = df_filtered[
    (df_filtered["Interval"] >= int_range[0]) & (df_filtered["Interval"] <= int_range[1])
]

st.markdown(f"**Showing {len(df_filtered)} of {len(df_logs)} records**")

# Display table
st.dataframe(
    df_filtered.style.format({
        "IEX Price (₹)": "₹{:,.0f}",
        "Net Cost (₹)": "₹{:,.0f}",
        "Solar (MW)": "{:.1f}",
        "Wind (MW)": "{:.1f}",
        "Demand (MW)": "{:.1f}",
        "Grid Import (MW)": "{:.1f}",
        "Grid Export (MW)": "{:.1f}",
        "Shortfall (MW)": "{:.2f}",
        "Carbon (tCO₂)": "{:.1f}",
    }),
    use_container_width=True,
    height=450,
)

# CSV Export
csv_data = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="📥 Download Filtered Log as CSV",
    data=csv_data,
    file_name=f"gridmind_decision_log_{orch.logger.run_id}.csv",
    mime="text/csv",
)
